# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: tcfg 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = 'tcfg'
  s.version = '0.2.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['robert schultheis']
  s.date = '2017-04-28'
  s.description = 'A tiered approach to configuration which allows for full control of your test suite through environment variables'
  s.email = 'robert.schultheis@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'lib/tcfg.rb',
    'lib/tcfg/tcfg_base.rb',
    'lib/tcfg/tcfg_helper.rb',
    'lib/tcfg/tcfg_module.rb'
  ]
  s.homepage = 'http://github.com/rschultheis/tcfg'
  s.licenses = ['MIT']
  s.rubygems_version = '2.5.1'
  s.summary = 'Test suite configuration for the real world'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('activesupport', ['>= 0'])
      s.add_development_dependency('jeweler', ['>= 0'])
      s.add_development_dependency('rspec', ['>= 0'])
      s.add_development_dependency('rubocop', ['>= 0'])
      s.add_development_dependency('yard', ['>= 0'])
    else
      s.add_dependency('activesupport', ['>= 0'])
      s.add_dependency('jeweler', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('rubocop', ['>= 0'])
      s.add_dependency('yard', ['>= 0'])
    end
  else
    s.add_dependency('activesupport', ['>= 0'])
    s.add_dependency('jeweler', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('rubocop', ['>= 0'])
    s.add_dependency('yard', ['>= 0'])
  end
end
